### ISSUE TITLE
真正的代码艺术家的作品居然没人气

### ISSUE THREAD

**Issue by hugetiny** [COLOR-SKY/ID-INVADED-WINDOWED#1]
了解下，交个朋友

**Comment by COLOR-SKY** [comment]
自己玩儿着爽就够了hhh

**Comment by COLOR-SKY** [comment]
> 了解下，交个朋友

自己玩儿着爽就够了hhh

**Comment by COLOR-SKY** [comment]
> 了解下，交个朋友

咱们自己玩儿着爽就够了hhh

**Comment by hugetiny** [comment]
一觉醒来47颗星星了！

**Comment by hugetiny** [comment]
666666
以前记得有个逼乎上的bull shit generator 其实是很简单的一个项目，星很高

**Comment by COLOR-SKY** [comment]
> 666666
> 以前记得有个逼乎上的bull shit generator 其实是很简单的一个项目，星很高

我觉得创意挺不错的，我们一谈文章生成就会想到NLP，结果作者用简单的方法实现了出彩的效果，说实话看到源码之前我也被惊到了，所以我觉得狗屁不通文章生成是值得拿高星的

**Comment by hugetiny** [comment]
> > 666666
> > 以前记得有个逼乎上的bull shit generator 其实是很简单的一个项目，星很高
> 
> 我觉得创意挺不错的，我们一谈文章生成就会想到NLP，结果作者用简单的方法实现了出彩的效果，说实话看到源码之前我也被惊到了，所以我觉得狗屁不通文章生成是值得拿高星的

的确有创意
