### ISSUE TITLE
小白提问

### ISSUE THREAD

**Issue by jerry460** [COLOR-SKY/ID-INVADED-WINDOWED#11]
请问大佬，要怎么做才能出现视频中的效果？是下好库以后运行pyc文件吗？

**Comment by COLOR-SKY** [comment]
逐帧匹配窗口动画

**Comment by jerry460** [comment]
如何匹配？将原op下载下来后导入吗？
感谢大佬抽空回复

**Comment by COLOR-SKY** [comment]
> 如何匹配？将原op下载下来后导入吗？
> 感谢大佬抽空回复

对头，整个op有4483帧，我逐帧做窗口动画以及各个窗口内需要填充的画面。
所以连续做了20来天吧23333

**Comment by jerry460** [comment]
感谢大佬解惑

**Comment by jerry460** [comment]
已star＋三连

**Comment by jerry460** [comment]
已star＋三连
