### ISSUE TITLE
路径错误？

### ISSUE THREAD

**Issue by huangshi10492** [COLOR-SKY/ID-INVADED-WINDOWED#4]
![image](https://user-images.githubusercontent.com/42275197/77822207-907f0f80-712b-11ea-90e5-11fe70a533e5.png)

**Comment by COLOR-SKY** [comment]
需要把python文件夹设置为source root，第一种方法是在Pycharm里右键文件夹Mark Directory as -> Souces root, 不过你使用的是VSCode, 所以第二种方法是在import dancywindow前
import sys
sys.path.append('<dancywindow.py所在目录>') # 如  sys.path.append("D://ID-INVADED-WINDOWED//Python//")

运行cxk.py需要配备[cudnn](https://developer.nvidia.com/cudnn)和[openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose)

**Comment by huangshi10492** [comment]
嗯，解决了
感觉python对vscode还是不太友好😥，只能在调试下运行

**Comment by huangshi10492** [comment]
作者继续加油，做出更有趣的东西

**Comment by luojunyuan** [comment]
> 嗯，解决了
> 感觉python对vscode还是不太友好😥，只能在调试下运行

你可以尝试 Code Runner 这个插件
