### ISSUE TITLE
运行程序报错NameError: name 'winsize' is not defined

### ISSUE THREAD

**Issue by moyu284** [COLOR-SKY/ID-INVADED-WINDOWED#9]

**Comment by COLOR-SKY** [comment]
这是在python中导入其它非modeld的.py文件的普遍问题。
解决方法一：请参考 https://stackoverflow.com/a/56151144 
解决方法二：
使用pycharm，并将dancywindow.py所在的文件夹标记为根目录
![QQ截图20200408024608](https://user-images.githubusercontent.com/21962518/78753074-3825ea00-7943-11ea-9759-af3c1f7369b0.png)

**Comment by moyu284** [comment]
pycharm标记为根目录了还是提示

**Comment by COLOR-SKY** [comment]
> pycharm标记为根目录了还是提示

这个不应该啊，发个截图我看看？

**Comment by moyu284** [comment]
![image](https://user-images.githubusercontent.com/38548383/78890566-77198400-7a98-11ea-96c1-d77f73880beb.png)

**Comment by Mealoore** [comment]
同样的错误诶

**Comment by COLOR-SKY** [comment]
> 同样的错误诶

你的root source是Python文件夹，而dancywindow.py在example目录下，就像我最初跟你讲的那样。
> 使用pycharm，并将dancywindow.py所在的文件夹标记为根目录

**Comment by moyu284** [comment]
![image](https://user-images.githubusercontent.com/38548383/78994527-e4014c80-7b72-11ea-821c-9c0483801e11.png)
example目录标记为根源之后。。。。。另外你的程序我克隆下来之后没有改过文件位置

**Comment by Mealoore** [comment]
设置根目录和sys.path.append效果一样吧？我用了sys.path.append，也试过直接把dancywindow.py放在系统包目录下，还是会出错(PS:我github上的是直接fork的，没有动过)

**Comment by COLOR-SKY** [comment]
> 设置根目录和sys.path.append效果一样吧？我用了sys.path.append，也试过直接把dancywindow.py放在系统包目录下，还是会出错(PS:我github上的是直接fork的，没有动过)

sys.path.append 只对程序找到dancywindow.py的路径有帮助，但是import是要将dancywindow.py作为一个model导入，因此需要用pycharm将dancywindow.py所在的路径设置为根目录，或用https://stackoverflow.com/a/56151144的方法。从github上下载到运行的教程我已经在bilibili上更新了。

**Comment by COLOR-SKY** [comment]
> ![image](https://user-images.githubusercontent.com/38548383/78994527-e4014c80-7b72-11ea-821c-9c0483801e11.png)
> example目录标记为根源之后。。。。。另外你的程序我克隆下来之后没有改过文件位置

很遗憾我这边使用pycharm无法复现这个错误，路径设置正确的话pycharm会自动弹出补全内容
![image](https://user-images.githubusercontent.com/21962518/79047427-6c6c0580-7be4-11ea-99bb-ff1fae8dc8c9.png) 这个问题是导入其它python文件时发生的，你可以以“pycharm导入其它py文件”为关键词查找相关资料。
